name: Publish Release

on:
  workflow_run:
    workflows: [ Generate Binaries ]
    types:
      - completed

jobs:
  call-final-workflow-in-bundler-repo:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: cloud-py-api/py_bundler/.github/workflows/generate-binaries-final.yml@main
    with:
      bin_prefix: demo_

  # this probably will be your custom step, modify(rewrite from scratch) it as you wish.
  draft_release:
    needs: [call-final-workflow-in-bundler-repo]
    name: Create Release
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Collect binaries
        uses: actions/download-artifact@v3
        with:
          name: cp_binaries
          path: cp_binaries

      - name: Get Last Tag
        id: last_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest

      - name: Create release draft
        uses: ncipollo/release-action@v1.11.2
        with:
          allowUpdates: true
          tag: ${{ steps.last_tag.outputs.tag }}
          commit: ${{ github.ref }}
          draft: false
          artifacts: cp_binaries/*
          artifactErrorsFailBuild: true